### ISSUE TITLE
Content added by my migration script has subtitles, but does not show subtitles in player.

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#417]
See `Terraferma` in the `Rob Reynolds' test` collection: https://yvideodev.byu.edu/manager/c10303d8-f685-4cae-a968-759d34c5ce0c

**Comment by reynoldsnlp** [comment]
The transcript is displayed, but clicking the skip icons does nothing, and the `CC` icon is not available in the player control panel.

**Comment by reynoldsnlp** [comment]
```js
Uncaught TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.
    at d.value (FilePlayer.js:404:19)
    at u.value (Player.js:372:21)
    at O.seekTo (ReactPlayer.js:152:22)
    at handleSeekChange (PlayerContainer.jsx:260:11)
    at onClick (index.jsx:162:28)
    at Object.u (react-dom.production.min.js:14:84)
    at d (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at g (react-dom.production.min.js:15:72)
    at at (react-dom.production.min.js:52:170)
```

**Comment by reynoldsnlp** [comment]
Turns out my subtitles JSON had `HH:MM:SS.SSS` instead of `S.SSS`. Fixed!
